// Purpose: Realistic mock data seeding all stores for development

import type {
  Recipe,
  RecipeCollection,
  PantryItem,
  GroceryItem,
  Store,
  Order,
  User,
  UserAddress,
} from '../types';

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Cacio e Pepe',
    description: 'The Roman classic — silky pasta with aged pecorino and black pepper. Deceptively simple, deeply satisfying.',
    imageUri: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    blurhash: 'LKF~Ws%2IUM{~qj[WBj[00WB-;of',
    cookTimeMinutes: 20,
    difficulty: 'medium',
    importedFrom: 'instagram',
    source: '@pasta.everyday',
    savedAt: '2024-03-10T10:00:00Z',
    tags: ['vegetarian'],
    nutrition: { calories: 520, proteinG: 18, carbsG: 72, fatG: 18 },
    ingredients: [
      { id: 'i1', name: 'Spaghetti', quantity: 400, unit: 'g', category: 'grains' },
      { id: 'i2', name: 'Pecorino Romano', quantity: 100, unit: 'g', category: 'dairy' },
      { id: 'i3', name: 'Black Pepper', quantity: 2, unit: 'tsp', category: 'spices' },
      { id: 'i4', name: 'Pasta Water', quantity: 200, unit: 'ml', category: 'pantry' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Cook spaghetti in generously salted water until al dente.', timerMinutes: 10 },
      { stepNumber: 2, instruction: 'Toast black pepper in a dry pan over medium heat until fragrant.' },
      { stepNumber: 3, instruction: 'Reserve 1 cup pasta water. Drain pasta and add to pan with pepper.' },
      { stepNumber: 4, instruction: 'Off heat, add grated pecorino and toss vigorously with pasta water to form a creamy sauce.', timerMinutes: 3 },
    ],
  },
  {
    id: 'r2',
    title: 'Lasagna Bolognese',
    description: 'Layers of fresh pasta, slow-cooked meat ragù, and béchamel — the definitive Italian Sunday dish.',
    imageUri: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800',
    blurhash: 'LDEyE:~q00xu00Rj%Mt700WB-;of',
    cookTimeMinutes: 90,
    difficulty: 'hard',
    importedFrom: 'url',
    source: 'seriouseats.com',
    savedAt: '2024-03-08T14:00:00Z',
    tags: ['high-protein'],
    nutrition: { calories: 680, proteinG: 34, carbsG: 58, fatG: 32 },
    ingredients: [
      { id: 'i5', name: 'Ground Beef', quantity: 500, unit: 'g', category: 'proteins' },
      { id: 'i6', name: 'Lasagna Sheets', quantity: 250, unit: 'g', category: 'grains' },
      { id: 'i7', name: 'Whole Milk', quantity: 500, unit: 'ml', category: 'dairy' },
      { id: 'i8', name: 'Crushed Tomatoes', quantity: 400, unit: 'g', category: 'pantry' },
      { id: 'i9', name: 'Mozzarella', quantity: 200, unit: 'g', category: 'dairy' },
      { id: 'i10', name: 'Onion', quantity: 1, unit: 'large', category: 'produce' },
      { id: 'i11', name: 'Butter', quantity: 60, unit: 'g', category: 'dairy' },
      { id: 'i12', name: 'All-Purpose Flour', quantity: 60, unit: 'g', category: 'grains' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Brown ground beef with diced onion and garlic over high heat.', timerMinutes: 8 },
      { stepNumber: 2, instruction: 'Add crushed tomatoes, reduce heat, and simmer ragù for 45 minutes.', timerMinutes: 45 },
      { stepNumber: 3, instruction: 'Make béchamel: melt butter, whisk in flour, gradually add warm milk.', timerMinutes: 10 },
      { stepNumber: 4, instruction: 'Layer pasta, ragù, béchamel, and mozzarella. Repeat 3 times.' },
      { stepNumber: 5, instruction: 'Bake at 375°F for 35 minutes until bubbly and golden.', timerMinutes: 35 },
    ],
  },
  {
    id: 'r3',
    title: 'Miso Ramen',
    description: 'Rich, deeply umami broth with handmade noodles, soft-boiled egg, and crispy pork belly.',
    imageUri: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800',
    blurhash: 'LDEL;F~q00x]00Rj%Mt7?bWB-;j[',
    cookTimeMinutes: 45,
    difficulty: 'medium',
    importedFrom: 'tiktok',
    source: '@ramenlord',
    savedAt: '2024-03-07T09:00:00Z',
    tags: ['dairy-free', 'high-protein'],
    nutrition: { calories: 590, proteinG: 38, carbsG: 62, fatG: 22 },
    ingredients: [
      { id: 'i13', name: 'Ramen Noodles', quantity: 200, unit: 'g', category: 'grains' },
      { id: 'i14', name: 'Miso Paste', quantity: 3, unit: 'tbsp', category: 'condiments' },
      { id: 'i15', name: 'Pork Belly', quantity: 300, unit: 'g', category: 'proteins' },
      { id: 'i16', name: 'Soft Boiled Eggs', quantity: 2, unit: 'whole', category: 'proteins' },
      { id: 'i17', name: 'Chicken Stock', quantity: 1000, unit: 'ml', category: 'pantry' },
      { id: 'i18', name: 'Green Onions', quantity: 3, unit: 'stalks', category: 'produce' },
      { id: 'i19', name: 'Nori', quantity: 2, unit: 'sheets', category: 'pantry' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Simmer chicken stock with miso paste and sesame oil for 20 minutes.', timerMinutes: 20 },
      { stepNumber: 2, instruction: 'Pan-fry pork belly until crispy on all sides.', timerMinutes: 10 },
      { stepNumber: 3, instruction: 'Cook ramen noodles according to package directions.', timerMinutes: 4 },
      { stepNumber: 4, instruction: 'Assemble: noodles, hot broth, pork belly, halved egg, green onions, nori.' },
    ],
  },
  {
    id: 'r4',
    title: 'Pad Thai',
    description: 'Wok-fried rice noodles with shrimp, egg, bean sprouts, and a tangy tamarind sauce.',
    imageUri: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    blurhash: 'LBF=.800~qkC00IU%Mx]?bRj-;ay',
    cookTimeMinutes: 25,
    difficulty: 'medium',
    importedFrom: 'instagram',
    source: '@thai.kitchen',
    savedAt: '2024-03-06T11:00:00Z',
    tags: ['dairy-free', 'gluten-free'],
    nutrition: { calories: 480, proteinG: 28, carbsG: 68, fatG: 12 },
    ingredients: [
      { id: 'i20', name: 'Rice Noodles', quantity: 200, unit: 'g', category: 'grains' },
      { id: 'i21', name: 'Shrimp', quantity: 250, unit: 'g', category: 'proteins' },
      { id: 'i22', name: 'Eggs', quantity: 2, unit: 'whole', category: 'proteins' },
      { id: 'i23', name: 'Bean Sprouts', quantity: 100, unit: 'g', category: 'produce' },
      { id: 'i24', name: 'Tamarind Paste', quantity: 2, unit: 'tbsp', category: 'condiments' },
      { id: 'i25', name: 'Fish Sauce', quantity: 2, unit: 'tbsp', category: 'condiments' },
      { id: 'i26', name: 'Lime', quantity: 1, unit: 'whole', category: 'produce' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Soak rice noodles in warm water for 30 minutes, drain.' },
      { stepNumber: 2, instruction: 'Mix tamarind paste, fish sauce, sugar, and lime juice for the sauce.' },
      { stepNumber: 3, instruction: 'Stir-fry shrimp in hot wok until pink. Push aside, scramble eggs.' },
      { stepNumber: 4, instruction: 'Add noodles and sauce. Toss until coated. Top with bean sprouts and peanuts.' },
    ],
  },
  {
    id: 'r5',
    title: 'Chicken Tacos al Pastor',
    description: 'Marinated chicken with pineapple, charred to perfection, served on warm corn tortillas.',
    imageUri: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    blurhash: 'LCEG{H~q00xZ00Rj%Mt700WB-;of',
    cookTimeMinutes: 30,
    difficulty: 'easy',
    importedFrom: 'tiktok',
    source: '@mexicana.cooks',
    savedAt: '2024-03-05T15:00:00Z',
    tags: ['dairy-free', 'gluten-free'],
    nutrition: { calories: 420, proteinG: 32, carbsG: 44, fatG: 14 },
    ingredients: [
      { id: 'i27', name: 'Chicken Thighs', quantity: 600, unit: 'g', category: 'proteins' },
      { id: 'i28', name: 'Corn Tortillas', quantity: 8, unit: 'whole', category: 'grains' },
      { id: 'i29', name: 'Pineapple', quantity: 150, unit: 'g', category: 'produce' },
      { id: 'i30', name: 'Chipotle in Adobo', quantity: 2, unit: 'tbsp', category: 'condiments' },
      { id: 'i31', name: 'Cilantro', quantity: 1, unit: 'bunch', category: 'produce' },
      { id: 'i32', name: 'White Onion', quantity: 1, unit: 'medium', category: 'produce' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Blend chipotle, pineapple juice, garlic, and spices for marinade.' },
      { stepNumber: 2, instruction: 'Marinate chicken thighs for at least 30 minutes.', timerMinutes: 30 },
      { stepNumber: 3, instruction: 'Grill or pan-sear chicken until charred and cooked through.', timerMinutes: 12 },
      { stepNumber: 4, instruction: 'Slice thin, serve on warm tortillas with pineapple, onion, and cilantro.' },
    ],
  },
  {
    id: 'r6',
    title: 'Black Bean Enchiladas',
    description: 'Hearty vegetarian enchiladas loaded with black beans, roasted peppers, and smoky red sauce.',
    imageUri: 'https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=800',
    blurhash: 'LDDc*?~q00xu00Rj%Mt700WB-;of',
    cookTimeMinutes: 40,
    difficulty: 'easy',
    importedFrom: 'manual',
    source: 'My Kitchen',
    savedAt: '2024-03-04T18:00:00Z',
    tags: ['vegetarian', 'gluten-free'],
    nutrition: { calories: 390, proteinG: 16, carbsG: 58, fatG: 10 },
    ingredients: [
      { id: 'i33', name: 'Black Beans', quantity: 400, unit: 'g', category: 'pantry' },
      { id: 'i34', name: 'Flour Tortillas', quantity: 8, unit: 'whole', category: 'grains' },
      { id: 'i35', name: 'Red Enchilada Sauce', quantity: 400, unit: 'ml', category: 'condiments' },
      { id: 'i36', name: 'Cheddar Cheese', quantity: 150, unit: 'g', category: 'dairy' },
      { id: 'i37', name: 'Red Bell Pepper', quantity: 2, unit: 'whole', category: 'produce' },
      { id: 'i38', name: 'Cumin', quantity: 1, unit: 'tsp', category: 'spices' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Roast bell peppers at 400°F for 20 minutes until charred.', timerMinutes: 20 },
      { stepNumber: 2, instruction: 'Mix drained beans with roasted peppers, cumin, salt, and half the cheese.' },
      { stepNumber: 3, instruction: 'Fill tortillas, roll tightly, place seam-down in baking dish.' },
      { stepNumber: 4, instruction: 'Pour enchilada sauce over top, cover with remaining cheese.', },
      { stepNumber: 5, instruction: 'Bake at 375°F for 20 minutes until bubbly.', timerMinutes: 20 },
    ],
  },
  {
    id: 'r7',
    title: 'Greek Salad with Grilled Halloumi',
    description: 'Fresh tomatoes, cucumber, olives, and crispy halloumi with herby oregano dressing.',
    imageUri: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    blurhash: 'LAFA:N~q00xu00Rj%Mt700WB-;of',
    cookTimeMinutes: 15,
    difficulty: 'easy',
    importedFrom: 'url',
    source: 'ottolenghi.co.uk',
    savedAt: '2024-03-03T12:00:00Z',
    tags: ['vegetarian', 'gluten-free', 'mediterranean'],
    nutrition: { calories: 340, proteinG: 18, carbsG: 14, fatG: 24 },
    ingredients: [
      { id: 'i39', name: 'Halloumi', quantity: 250, unit: 'g', category: 'dairy' },
      { id: 'i40', name: 'Cherry Tomatoes', quantity: 200, unit: 'g', category: 'produce' },
      { id: 'i41', name: 'Cucumber', quantity: 1, unit: 'large', category: 'produce' },
      { id: 'i42', name: 'Kalamata Olives', quantity: 80, unit: 'g', category: 'pantry' },
      { id: 'i43', name: 'Red Onion', quantity: 0.5, unit: 'medium', category: 'produce' },
      { id: 'i44', name: 'Dried Oregano', quantity: 1, unit: 'tsp', category: 'spices' },
      { id: 'i45', name: 'Olive Oil', quantity: 3, unit: 'tbsp', category: 'pantry' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Slice halloumi and grill in dry pan until golden on each side.', timerMinutes: 6 },
      { stepNumber: 2, instruction: 'Chop tomatoes, cucumber, and red onion. Combine with olives.' },
      { stepNumber: 3, instruction: 'Whisk olive oil, lemon juice, and dried oregano for dressing.' },
      { stepNumber: 4, instruction: 'Toss salad with dressing, top with warm grilled halloumi.' },
    ],
  },
  {
    id: 'r8',
    title: 'Hummus Bowl with Roasted Vegetables',
    description: 'Creamy tahini hummus topped with oven-roasted seasonal vegetables and pomegranate seeds.',
    imageUri: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    blurhash: 'LDFA?I~q00xu00Rj%Mt700WB-;of',
    cookTimeMinutes: 35,
    difficulty: 'easy',
    importedFrom: 'instagram',
    source: '@plant.plate',
    savedAt: '2024-03-02T13:00:00Z',
    tags: ['vegan', 'gluten-free', 'mediterranean', 'dairy-free'],
    nutrition: { calories: 310, proteinG: 12, carbsG: 38, fatG: 14 },
    ingredients: [
      { id: 'i46', name: 'Chickpeas', quantity: 400, unit: 'g', category: 'pantry' },
      { id: 'i47', name: 'Tahini', quantity: 3, unit: 'tbsp', category: 'condiments' },
      { id: 'i48', name: 'Zucchini', quantity: 2, unit: 'medium', category: 'produce' },
      { id: 'i49', name: 'Eggplant', quantity: 1, unit: 'medium', category: 'produce' },
      { id: 'i50', name: 'Garlic', quantity: 3, unit: 'cloves', category: 'produce' },
      { id: 'i51', name: 'Lemon Juice', quantity: 2, unit: 'tbsp', category: 'produce' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Roast cubed zucchini and eggplant at 425°F with olive oil and salt.', timerMinutes: 25 },
      { stepNumber: 2, instruction: 'Blend chickpeas, tahini, lemon juice, garlic, and ice water until silky smooth.', timerMinutes: 5 },
      { stepNumber: 3, instruction: 'Spread hummus in bowls, top with roasted vegetables and pomegranate.' },
    ],
  },
  {
    id: 'r9',
    title: 'Smash Burgers',
    description: 'Thin crispy-edged beef patties with American cheese, pickles, and special sauce on brioche.',
    imageUri: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    blurhash: 'LBFiPK~q00xu00Rj%Mt700WB-;of',
    cookTimeMinutes: 20,
    difficulty: 'easy',
    importedFrom: 'tiktok',
    source: '@burger.lab',
    savedAt: '2024-03-01T17:00:00Z',
    tags: ['high-protein'],
    nutrition: { calories: 720, proteinG: 42, carbsG: 48, fatG: 36 },
    ingredients: [
      { id: 'i52', name: 'Ground Beef 80/20', quantity: 500, unit: 'g', category: 'proteins' },
      { id: 'i53', name: 'Brioche Buns', quantity: 4, unit: 'whole', category: 'bakery' },
      { id: 'i54', name: 'American Cheese', quantity: 4, unit: 'slices', category: 'dairy' },
      { id: 'i55', name: 'Dill Pickles', quantity: 8, unit: 'slices', category: 'condiments' },
      { id: 'i56', name: 'Mayonnaise', quantity: 3, unit: 'tbsp', category: 'condiments' },
      { id: 'i57', name: 'Yellow Mustard', quantity: 1, unit: 'tbsp', category: 'condiments' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Form beef into 2oz loosely packed balls. Season with salt and pepper.' },
      { stepNumber: 2, instruction: 'Heat cast iron skillet until screaming hot. Add beef balls and smash flat immediately.', timerMinutes: 2 },
      { stepNumber: 3, instruction: 'Cook until edges are crispy and brown. Flip, add cheese, cover for 30 seconds.' },
      { stepNumber: 4, instruction: 'Mix mayo, ketchup, mustard for sauce. Build burgers with sauce and pickles.' },
    ],
  },
  {
    id: 'r10',
    title: 'Avocado Toast with Poached Eggs',
    description: 'Thick sourdough, smashed avocado, perfectly poached eggs, everything bagel seasoning.',
    imageUri: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
    blurhash: 'LCFC:N~q00xu00Rj%Mt700WB-;of',
    cookTimeMinutes: 12,
    difficulty: 'easy',
    importedFrom: 'instagram',
    source: '@morning.eats',
    savedAt: '2024-02-28T09:00:00Z',
    tags: ['vegetarian', 'dairy-free'],
    nutrition: { calories: 380, proteinG: 14, carbsG: 32, fatG: 22 },
    ingredients: [
      { id: 'i58', name: 'Sourdough Bread', quantity: 2, unit: 'thick slices', category: 'bakery' },
      { id: 'i59', name: 'Avocado', quantity: 1, unit: 'large', category: 'produce' },
      { id: 'i60', name: 'Eggs', quantity: 2, unit: 'whole', category: 'proteins' },
      { id: 'i61', name: 'Lemon', quantity: 0.5, unit: 'whole', category: 'produce' },
      { id: 'i62', name: 'Red Pepper Flakes', quantity: 0.5, unit: 'tsp', category: 'spices' },
      { id: 'i63', name: 'Everything Bagel Seasoning', quantity: 1, unit: 'tsp', category: 'spices' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Toast sourdough until deep golden and crispy.' },
      { stepNumber: 2, instruction: 'Poach eggs in simmering water with a splash of vinegar for 3 minutes.', timerMinutes: 3 },
      { stepNumber: 3, instruction: 'Smash avocado with lemon juice, salt. Spread thickly on toast.' },
      { stepNumber: 4, instruction: 'Top with poached eggs, everything bagel seasoning, and chili flakes.' },
    ],
  },
];

const tomorrow = new Date();
tomorrow.setDate(tomorrow.getDate() + 1);
const inTwoDays = new Date();
inTwoDays.setDate(inTwoDays.getDate() + 2);
const inFiveDays = new Date();
inFiveDays.setDate(inFiveDays.getDate() + 5);
const inTenDays = new Date();
inTenDays.setDate(inTenDays.getDate() + 10);

export const MOCK_PANTRY: PantryItem[] = [
  { id: 'p1', name: 'Eggs', quantity: 6, unit: 'whole', category: 'proteins', addedAt: '2024-03-10T08:00:00Z', addedVia: 'manual', expiryDate: tomorrow.toISOString() },
  { id: 'p2', name: 'Whole Milk', quantity: 500, unit: 'ml', category: 'dairy', addedAt: '2024-03-09T08:00:00Z', addedVia: 'receipt', expiryDate: inTwoDays.toISOString() },
  { id: 'p3', name: 'Spinach', quantity: 100, unit: 'g', category: 'produce', addedAt: '2024-03-08T08:00:00Z', addedVia: 'manual', expiryDate: inTwoDays.toISOString() },
  { id: 'p4', name: 'Chicken Thighs', quantity: 400, unit: 'g', category: 'proteins', addedAt: '2024-03-10T08:00:00Z', addedVia: 'receipt', expiryDate: inFiveDays.toISOString() },
  { id: 'p5', name: 'Garlic', quantity: 6, unit: 'cloves', category: 'produce', addedAt: '2024-03-01T08:00:00Z', addedVia: 'manual' },
  { id: 'p6', name: 'Olive Oil', quantity: 300, unit: 'ml', category: 'pantry', addedAt: '2024-03-01T08:00:00Z', addedVia: 'manual' },
  { id: 'p7', name: 'Black Pepper', quantity: 50, unit: 'g', category: 'spices', addedAt: '2024-02-15T08:00:00Z', addedVia: 'manual' },
  { id: 'p8', name: 'Spaghetti', quantity: 400, unit: 'g', category: 'grains', addedAt: '2024-03-05T08:00:00Z', addedVia: 'receipt' },
  { id: 'p9', name: 'Crushed Tomatoes', quantity: 400, unit: 'g', category: 'pantry', addedAt: '2024-03-05T08:00:00Z', addedVia: 'receipt' },
  { id: 'p10', name: 'Onion', quantity: 3, unit: 'medium', category: 'produce', addedAt: '2024-03-01T08:00:00Z', addedVia: 'manual' },
  { id: 'p11', name: 'Miso Paste', quantity: 200, unit: 'g', category: 'condiments', addedAt: '2024-03-01T08:00:00Z', addedVia: 'scan', expiryDate: inTenDays.toISOString() },
  { id: 'p12', name: 'Soy Sauce', quantity: 250, unit: 'ml', category: 'condiments', addedAt: '2024-03-01T08:00:00Z', addedVia: 'manual' },
  { id: 'p13', name: 'Avocado', quantity: 2, unit: 'whole', category: 'produce', addedAt: '2024-03-10T08:00:00Z', addedVia: 'receipt' },
  { id: 'p14', name: 'Chickpeas', quantity: 400, unit: 'g', category: 'pantry', addedAt: '2024-03-05T08:00:00Z', addedVia: 'receipt' },
  { id: 'p15', name: 'Frozen Peas', quantity: 300, unit: 'g', category: 'frozen', addedAt: '2024-02-20T08:00:00Z', addedVia: 'manual' },
  { id: 'p16', name: 'Sourdough Bread', quantity: 1, unit: 'loaf', category: 'bakery', addedAt: '2024-03-10T08:00:00Z', addedVia: 'manual', expiryDate: inFiveDays.toISOString() },
  { id: 'p17', name: 'Lemon', quantity: 4, unit: 'whole', category: 'produce', addedAt: '2024-03-07T08:00:00Z', addedVia: 'manual' },
  { id: 'p18', name: 'Cumin', quantity: 30, unit: 'g', category: 'spices', addedAt: '2024-02-10T08:00:00Z', addedVia: 'manual' },
  { id: 'p19', name: 'Orange Juice', quantity: 500, unit: 'ml', category: 'beverages', addedAt: '2024-03-08T08:00:00Z', addedVia: 'receipt', expiryDate: inFiveDays.toISOString() },
  { id: 'p20', name: 'All-Purpose Flour', quantity: 500, unit: 'g', category: 'grains', addedAt: '2024-03-01T08:00:00Z', addedVia: 'manual' },
];

export const MOCK_GROCERY_LIST: GroceryItem[] = [
  { id: 'g1', name: 'Pecorino Romano', quantity: 100, unit: 'g', checked: false, aisle: 'Dairy & Eggs', recipeId: 'r1', recipeTitle: 'Cacio e Pepe' },
  { id: 'g2', name: 'Ground Beef 80/20', quantity: 500, unit: 'g', checked: false, aisle: 'Meat & Seafood', recipeId: 'r9', recipeTitle: 'Smash Burgers' },
  { id: 'g3', name: 'Brioche Buns', quantity: 4, unit: 'whole', checked: false, aisle: 'Bakery', recipeId: 'r9', recipeTitle: 'Smash Burgers' },
  { id: 'g4', name: 'Shrimp', quantity: 250, unit: 'g', checked: false, aisle: 'Meat & Seafood', recipeId: 'r4', recipeTitle: 'Pad Thai' },
  { id: 'g5', name: 'Rice Noodles', quantity: 200, unit: 'g', checked: false, aisle: 'Grains & Pasta', recipeId: 'r4', recipeTitle: 'Pad Thai' },
  { id: 'g6', name: 'Tamarind Paste', quantity: 1, unit: 'jar', checked: false, aisle: 'Condiments & Sauces', recipeId: 'r4', recipeTitle: 'Pad Thai' },
  { id: 'g7', name: 'Halloumi', quantity: 250, unit: 'g', checked: false, aisle: 'Dairy & Eggs', recipeId: 'r7', recipeTitle: 'Greek Salad with Grilled Halloumi' },
  { id: 'g8', name: 'Cherry Tomatoes', quantity: 200, unit: 'g', checked: true, aisle: 'Produce', recipeId: 'r7', recipeTitle: 'Greek Salad with Grilled Halloumi' },
  { id: 'g9', name: 'Kalamata Olives', quantity: 80, unit: 'g', checked: true, aisle: 'Pantry', recipeId: 'r7', recipeTitle: 'Greek Salad with Grilled Halloumi' },
  { id: 'g10', name: 'Pork Belly', quantity: 300, unit: 'g', checked: true, aisle: 'Meat & Seafood', recipeId: 'r3', recipeTitle: 'Miso Ramen' },
  { id: 'g11', name: 'Ramen Noodles', quantity: 200, unit: 'g', checked: true, aisle: 'Grains & Pasta', recipeId: 'r3', recipeTitle: 'Miso Ramen' },
  { id: 'g12', name: 'Nori', quantity: 1, unit: 'pack', checked: false, aisle: 'Pantry', recipeId: 'r3', recipeTitle: 'Miso Ramen' },
];

export const MOCK_COLLECTIONS: RecipeCollection[] = [
  {
    id: 'col-1',
    name: 'Weeknight Dinners',
    description: 'Quick meals ready in under 30 minutes',
    coverImageUri: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    recipeIds: ['r1', 'r4', 'r5', 'r10'],
    createdAt: '2024-03-01T10:00:00Z',
    emoji: '🍳',
  },
  {
    id: 'col-2',
    name: 'Date Night',
    description: 'Impress with these show-stoppers',
    coverImageUri: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800',
    recipeIds: ['r2', 'r3', 'r7'],
    createdAt: '2024-03-05T14:00:00Z',
    emoji: '🍷',
  },
  {
    id: 'col-3',
    name: 'Plant Power',
    description: 'Vegetarian & vegan favorites',
    coverImageUri: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    recipeIds: ['r6', 'r7', 'r8', 'r10'],
    createdAt: '2024-03-08T09:00:00Z',
    emoji: '🥬',
  },
  {
    id: 'col-4',
    name: 'Meal Prep Sunday',
    description: 'Batch-cook recipes that keep well',
    coverImageUri: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800',
    recipeIds: ['r2', 'r6', 'r8'],
    createdAt: '2024-03-09T11:00:00Z',
    emoji: '📦',
  },
];

export const MOCK_STORES: Store[] = [
  { id: 's1', name: 'Kroger', logo: 'kroger', distance: 0.8, supportsPickup: true, isInstacart: true },
  { id: 's2', name: 'Walmart', logo: 'walmart', distance: 1.2, supportsPickup: true, isInstacart: false },
  { id: 's3', name: 'H-Mart', logo: 'hmart', distance: 2.1, supportsPickup: true, isInstacart: true },
  { id: 's4', name: 'Costco', logo: 'costco', distance: 3.0, supportsPickup: true, isInstacart: true },
  { id: 's5', name: 'Sprouts', logo: 'sprouts', distance: 2.8, supportsPickup: true, isInstacart: true },
  { id: 's6', name: 'Albertsons', logo: 'albertsons', distance: 4.7, supportsPickup: true, isInstacart: true },
];

export const MOCK_ORDER: Order = {
  id: 'o1',
  store: MOCK_STORES[0],
  items: MOCK_GROCERY_LIST.filter((i) => !i.checked).slice(0, 5),
  status: 'preparing',
  estimatedPickup: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
  subtotal: 34.87,
  placedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
};

export const MOCK_ADDRESSES: UserAddress[] = [
  {
    id: 'addr-1',
    label: 'Home',
    street: '1234 Oak Street',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    isDefault: true,
  },
  {
    id: 'addr-2',
    label: 'Work',
    street: '500 Congress Ave',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    isDefault: false,
  },
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Rivera',
  email: 'alex@example.com',
  preferences: {
    dietaryTags: ['vegetarian', 'gluten-free'],
    allergies: ['peanuts'],
    cuisines: ['Italian', 'Asian', 'Mediterranean'],
    householdSize: 2,
  },
  connectedAccounts: {
    instagram: '@alex.eats',
  },
  addresses: MOCK_ADDRESSES,
  defaultAddressId: 'addr-1',
};
